export const INQUIRY_TITLE_MAX_LENGTH = 200;
export const INQUIRY_CONTENT_MAX_LENGTH = 5000;
export const INQUIRY_ANSWER_MAX_LENGTH = 5000;
export const ADMIN_INQUIRY_LIST_LIMIT = 50;
export const CONSUMER_INQUIRY_LIST_LIMIT = 50;
export const INQUIRY_MESSAGE_PAGE_SIZE = 10;
export const ADMIN_NOTIFICATION_BADGE_MAX = 99;
export const ADMIN_NOTIFICATION_DROPDOWN_LIMIT = 5;

export const INQUIRY_MESSAGE_AUTHOR = {
  CONSUMER: 'consumer',
  ADMIN: 'admin',
} as const;
