export const PRICING = {
  BOOK_UNIT_PRICE_KRW: 10,
  PRICE_PER_PAGE_KRW: 5,
} as const;

export const SHIPPING = {
  BASE_FEE_KRW: 2000,
  JEJU_SURCHARGE_KRW: 3000,
  REMOTE_AREA_SURCHARGE_KRW: 5000,
  FREE_SHIPPING_THRESHOLD_KRW: 10000,
} as const;
