export const PRODUCT_NAME_MAX_LENGTH = 100;
export const PRODUCT_SLUG_MAX_LENGTH = 100;
export const PRODUCT_SIZE_MAX_LENGTH = 50;
export const PRODUCT_DESCRIPTION_MAX_LENGTH = 2000;
export const PRODUCT_PRICE_MAX = 1_000_000;
