export const TOSS_ERROR_CODES = {
  PAY_PROCESS_CANCELED: 'PAY_PROCESS_CANCELED',
  PAY_PROCESS_ABORTED: 'PAY_PROCESS_ABORTED',
  REJECT_CARD_COMPANY: 'REJECT_CARD_COMPANY',
  USER_CANCEL: 'USER_CANCEL',
  NOT_SELECTED_PAYMENT_METHOD: 'NOT_SELECTED_PAYMENT_METHOD',
  NEED_AGREEMENT_WITH_REQUIRED_TERMS: 'NEED_AGREEMENT_WITH_REQUIRED_TERMS',
  NEED_CARD_PAYMENT_DETAIL: 'NEED_CARD_PAYMENT_DETAIL',
  NEED_REFUND_ACCOUNT_DETAIL: 'NEED_REFUND_ACCOUNT_DETAIL',
  EXCEED_DEPOSIT_AMOUNT_LIMIT: 'EXCEED_DEPOSIT_AMOUNT_LIMIT',
  PROVIDER_STATUS_UNHEALTHY: 'PROVIDER_STATUS_UNHEALTHY',
  UNSUPPORTED_TEST_PHASE_PAYMENT_METHOD: 'UNSUPPORTED_TEST_PHASE_PAYMENT_METHOD',
  NETWORK_ERROR: 'NETWORK_ERROR',
  INVALID_METHOD_TRANSACTION: 'INVALID_METHOD_TRANSACTION',
} as const;

export function getTossErrorCode(error: unknown): string | null {
  if (typeof error !== 'object' || error === null || !('code' in error)) {
    return null;
  }

  const { code } = error as Record<string, unknown>;
  return typeof code === 'string' ? code : null;
}
